## Batch nomalization & Layer nomalization

这个东西实在有点搞 直接写算例说明吧

In [2]:
import torch
import torch.nn as nn

x = torch.tensor([[[1,2,3], [3,3,3], [3,4,5]],
                  [[4,5,6], [3,3,3], [7,8,9]]], dtype=torch.float32)
# shape(batch_size=2, channels=3, length=3)
print(x)

batch_norm = nn.BatchNorm1d(3, affine=False)
x = batch_norm(x)
print(x)

tensor([[[1., 2., 3.],
         [3., 3., 3.],
         [3., 4., 5.]],

        [[4., 5., 6.],
         [3., 3., 3.],
         [7., 8., 9.]]])
tensor([[[-1.4638, -0.8783, -0.2928],
         [ 0.0000,  0.0000,  0.0000],
         [-1.3887, -0.9258, -0.4629]],

        [[ 0.2928,  0.8783,  1.4638],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.4629,  0.9258,  1.3887]]])


期望的输入shape为(batch_size, channels, length)

做法是在每个channel上，也即输入张量的第二个维度上，统计所有batch和length上的均值和方差，据此对这部分数据归一化，比如上例中第一个channel（也是dimension）上的数据就是123456

In [5]:
layer_norm = nn.LayerNorm(3, elementwise_affine=False)

y = torch.tensor([[[1,2,3], [3,3,3], [3,4,5]],
                  [[4,5,6], [3,3,3], [7,8,10]]], dtype=torch.float32)
print(y)

y = layer_norm(y)
print(y)

tensor([[[ 1.,  2.,  3.],
         [ 3.,  3.,  3.],
         [ 3.,  4.,  5.]],

        [[ 4.,  5.,  6.],
         [ 3.,  3.,  3.],
         [ 7.,  8., 10.]]])
tensor([[[-1.2247,  0.0000,  1.2247],
         [ 0.0000,  0.0000,  0.0000],
         [-1.2247,  0.0000,  1.2247]],

        [[-1.2247,  0.0000,  1.2247],
         [ 0.0000,  0.0000,  0.0000],
         [-1.0690, -0.2673,  1.3363]]])


layer nomalization 接收的shape为(batch_size, length, channels)

会作用于第三个维度，对每一个batch的每一个时间步上的数据按dimension归一化 

比如上面第一行输出就是对123 第二行是333……

In [6]:
instant_norm = nn.InstanceNorm1d(3)

z = torch.tensor([[[1,2,3], [3,3,3], [3,4,5]],
                  [[4,5,6], [3,3,3], [7,8,10]]], dtype=torch.float32)

print(z)
print(instant_norm(z))

tensor([[[ 1.,  2.,  3.],
         [ 3.,  3.,  3.],
         [ 3.,  4.,  5.]],

        [[ 4.,  5.,  6.],
         [ 3.,  3.,  3.],
         [ 7.,  8., 10.]]])
tensor([[[-1.2247,  0.0000,  1.2247],
         [ 0.0000,  0.0000,  0.0000],
         [-1.2247,  0.0000,  1.2247]],

        [[-1.2247,  0.0000,  1.2247],
         [ 0.0000,  0.0000,  0.0000],
         [-1.0690, -0.2673,  1.3363]]])
